name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Flutter build and deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Say start a build
        run: echo flutter build web

      - name: setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: Run a flutter build and deploy
        run: |
         flutter config --enable-web
         flutter pub get
         flutter build web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./build/web
